javascripts:
  workspace:
    - public/javascripts/rails.js
    - public/javascripts/jquery.textPlaceholder.js
    - public/javascripts/jquery.validate.min.js

stylesheets:
  common:
    - public/stylesheets/screen.css
    - public/stylesheets/venues.css