login: &login
  adapter: mysql
  username: root
  password: root
  host: localhost
  port: 3307

development:
  <<: *login
  database: venue_management_development

test:
  <<: *login
  database: venue_management_test

production:
  <<: *login
  database: venue_management_production